"""task moved

Revision ID: 6ab9364c7822
Revises: 4306d065ac5f
Create Date: 2023-03-27 15:26:36.342839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab9364c7822'
down_revision = '4306d065ac5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
