"""task 6 added

Revision ID: 91172f6039b9
Revises: aeeb51319b13
Create Date: 2023-03-26 15:12:54.942978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91172f6039b9'
down_revision = 'aeeb51319b13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
